<?php

namespace OC\BackBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnvalidatedObservation()
    {
        $qb = $this->createQueryBuilder('o')
            ->select('o')
          //  ->join('o.user', 'u')
           // ->join('o.image', 'i')
          //  ->where('u.id = o.user')
          //  ->andWhere('o.image = i.id')
            ->where('o.validated = 0')
        ;

        return $qb->getQuery()->getResult();
    }

}
