<?php

namespace OC\BackBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAllUsers()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.enabled = 1')
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
