<?php

namespace OC\CoreBundle\Repository;

/**
 * CodeCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
