<?php

namespace OC\CoreBundle\Repository;

/**
 * RangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangRepository extends \Doctrine\ORM\EntityRepository
{
}
