<?php

namespace OC\CoreBundle\Repository;

/**
 * StatutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutsRepository extends \Doctrine\ORM\EntityRepository
{
}
